/**
 * @author Benjamin Guirlet
 * @description
 *      Handler for the command 'play'.
 */


const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction, Client } = require( "discord.js" );

const ytdl = require( "ytdl-core" );
const ytsearch = require( "yt-search" );


const slashCommand = new SlashCommandBuilder()
	.setName( "play" )
	.setDescription( "Joue une musique, playlist ou le résultat d'une recherche passée en paramètre" )
	.addStringOption( option =>
		option.setName( "option" )
			.setDescription( "Lien de la musique/playlist ou une recherche." )
	);


/**
 * The commands function. It is executed when the slash command is called.
 * @param {CommandInteraction} interaction The interaction generated by the command execution.
 * @param {Client} client The bot's client.
 */
async function execute( interaction, client ) {
	// Checking is the member is in a voice channel.
	const member = await interaction.guild.members.fetch(interaction.user.id);
	const voiceChannel = member.voice; // TODO check with voice.channel to get voiceChannel connected
	console.log(voiceChannel)
	if ( !voiceChannel ) {
		await interaction.reply( "Tu dois être connecté dans un vocal!" );
		return;
	}

	// The user is connected in a voice channel.
	await interaction.reply( "nice!" );
}


module.exports = {
	data: slashCommand,
	execute
}