/**
 * @author Benjamin Guirlet
 * @file
 *		Handler for the shuffle command.
 */


const { checkUserIsConnected } = require( `${process.cwd()}/utils/utils` );

const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction, Client, MessageEmbed } = require( "discord.js" );


const slashCommand = new SlashCommandBuilder()
	.setName( "shuffle" )
	.setDescription( "Mélange la queue" );


/* ----------------------------------------------- */
/* FUNCTIONS                                       */
/* ----------------------------------------------- */
/**
 * The commands function. It is executed when the slash command is called.
 * @param {CommandInteraction} interaction The interaction generated by the command execution.
 * @param {Client} client The bot's client.
 */
async function execute( interaction, client ) {
	if ( !checkUserIsConnected( interaction ) ) return;

	if ( client.guildsData.queue.length <= 1 )
		return interaction.reply( "Il n'y a pas assez de musiques dans la queue" );

	const queue = client.guildsData.queue;
	const newQueue = [];
	let index;
	while ( queue.length != 0 ) {
		index = Math.floor( Math.random() * queue.length );
		newQueue.push( queue[index] );
		queue.splice( index, 1 );
	}

	client.guildsData.queue = newQueue;

	await interaction.reply( "La queue a été mélangée!" );
}


/* ----------------------------------------------- */
/* MODULE EXPORTS                                  */
/* ----------------------------------------------- */
module.exports = {
	data: slashCommand,
	execute
}