/**
 * @author Benjamin Guirlet
 * @description
 *      Handler for the command 'time'.
 */


const { EMBED_COLOR } = require( `${process.cwd()}/files/config.json` );
const { checkUserIsConnected, getIntDate } = require( `${process.cwd()}/utils/utils` );

const { SlashCommandBuilder } = require( "@discordjs/builders" );
const { CommandInteraction, Client, MessageEmbed } = require( "discord.js" );



const slashCommand = new SlashCommandBuilder()
	.setName( "time" )
	.setDescription( "Affiche le temps restant avant la fin de la musique." );


/* ----------------------------------------------- */
/* FUNCTIONS                                       */
/* ----------------------------------------------- */
/**
 * The commands function. It is executed when the slash command is called.
 * @param {CommandInteraction} interaction The interaction generated by the command execution.
 * @param {Client} client The bot's client.
 */
async function execute( interaction, client ) {
	if ( !(await checkUserIsConnected( interaction )) ) return;


	const guildId = interaction.guildId;
	if ( client.guildsData.has( guildId ) ) {
		const guildData = client.guildsData.get( guildId );
		const remainingTimeSeconds = guildData.currentSong.lengthSeconds - (getIntDate() - guildData.currentSong.intDate);
		const remainingTime = `${Math.floor( remainingTimeSeconds / 60 )}:${remainingTimeSeconds % 60}`;

		await interaction.reply( {
			embeds: [
				new MessageEmbed()
					.setColor( EMBED_COLOR )
					.setAuthor(
						`| Il reste [${remainingTime}] sur [${guildData.currentSong.duration}]!`,
						interaction.user.avatarURL()
					)
			]
		});
	}
	else {
		await interaction.reply({
			embeds: [
				new MessageEmbed()
					.setColor( EMBED_COLOR )
					.setAuthor( "| Le bot n'est pas connecté à un vocal!", interaction.user.avatarURL() )
			]
		});
	}
}


/* ----------------------------------------------- */
/* MODULE EXPORTS                                  */
/* ----------------------------------------------- */
module.exports = {
	data: slashCommand,
	execute
}